### ISSUE TITLE
Documentation needed on the return values of the class methods

### ISSUE THREAD

**Issue by Dogeek** [tsifrer/python-twitch-client#13]
Taking an example, I want to make a bot that behaves differently for subscribed users, followers etc...

to get subscriptions, I should use :

```
client = twitch.TwitchClient(client_id, oauth)

channel = client.channel.get()

subscribes = channel.get_subscriptions(args) #offset moving 100 at a time in a loop
```

so now, what exactly is in subscribes, it's a list, but how are users represented in python ?

twitch dev gives :
```
{

    "_total": 4,

    "subscriptions": [

        {

            "_id": "e5e2ddc37e74aa9636625e8d2cc2e54648a30418",

            "created_at": "2016-04-06T04:44:31Z",

            "sub_plan": "1000",

            "sub_plan_name": "Channel Subscription (mr_woodchuck)",

            "user": {

                "_id": "89614178",

                "bio": "Twitch staff member who is a heimerdinger main on the road to diamond.",

                "created_at": "2015-04-26T18:45:34Z",

                "display_name": "Mr_Woodchuck",

                "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/mr_woodchuck-profile_image-a8b10154f47942bc-300x300.jpeg",

                "name": "mr_woodchuck",

                "type": "staff",

                "updated_at": "2017-04-06T00:14:13Z"

            }

        },

    . . .

   ]

}
```
so to access the id of the first user, should I use ` subscribes[0].user.id_ ` ? 

Also I think you're missing the token revoke endpoint.

I also think you could add some image stuff to the library to parse images from the links, and have them accessible as python objects (using pillow maybe)

Also, sub_plan refers to sub tiers ? so 1000 is 4.99$, 2000 9.99$ and 6000(or 3000, read somewhere that 25$ subs count for 6 so just interpreting the data) 24.99$ ?

**Comment by tsifrer** [comment]
I agree that there is lack of documentation. What I was trying to avoid is documenting the actual output of the calls because Twitch might change/add a field at any time and the documentation would get outdated, so it's better to refer to their original documentation (ofc the explanation is missing in the docs).

I'll think about how to improve it. If you have any ideas, please feel free to either open an issue, comment here or even open a PR :)

Regarding the `id` field, all objects returned from twitch has an `_id` value inside which the code renames to `id` (also not documented, sorry) so to get the subscriber id you need to do `subscribers[0].user.id`

Token revoke point is definitely missing since I wasn't implementing anything regarding getting or revoking a token.

Images: Not sure if I want to add another dependency to the client. Might do an optional dependency, never the less, a good idea and something to think about.

About sub_plans: they weren't like that when I first implemented this and this client is a bit out of date with the actual twitch API. I'll need to invest some more time into it to add the correct endpoints an parsing (for example this client is completely missing the bits endpoints). Also TBH I currently have no idea how the sub tier system works because with these tiers and how it's interpreted. If you know how to iterpret it, please fell free to open a PR :)

Thanks for the detailed issue!
