### ISSUE TITLE
Dealing with 5xx errors

### ISSUE THREAD

**Issue by Volcyy** [tsifrer/python-twitch-client#16]
I've worked with the Twitch API before without using any library and the API returning a 5xx error code (internal server error) seems to be quite common. 
This appears to be a known issue, as several Twitch Developer Forum threads talk about it:
- [API throwing 500 errors](https://discuss.dev.twitch.tv/t/api-throwing-500-errors/1587)
- [502 Bad Gateway on API Calls causing up to 60% failure rate for cron jobs](https://discuss.dev.twitch.tv/t/502-bad-gateway-on-api-calls-causing-up-to-60-failure-rate-for-cron-jobs/1574)

TL;DR:
> Yes our API is flaky, yes we are working on increasing it's stability. Most of our apps have retry logic to minimize the impact of a request failing, I'd recommend the same approach for your cron jobs. Just make sure to cap the number of retries and use exponential backoff and you should be fine.

I think having the mentioned exponential backoff with a capped number of retries in a library for the API would be great. 

Looking at the source, it appears that the functions for requesting data are in [`base.py`](https://github.com/tsifrer/python-twitch-client/blob/master/twitch/api/base.py). 

Could something like this be implemented? I'd be more than happy to help, are there any guidelines that I should be aware of?

Thanks in advance!

**Comment by tsifrer** [comment]
Hey! Thanks for the interest in this API wrapper. The only "guidelines" so far are code style guidelines (using flake8 and flake8-import-order to check the styles) and to have >90% test coverage. Other than that I'm open to any suggestions/improvements :)

Also I think this is a great idea and should definitely be implemented. I unfortunately don't have time to do it for the next few weeks so if you want it, I'd be happy to review/merge and do a release :)

**Comment by Volcyy** [comment]
Alright, I added a basic implementation [on my fork](https://github.com/Volcyy/python-twitch-client/blob/api-error-handling/twitch/api/base.py). I hope that I did not miss anything 😄 

Basically, [`TwitchAPI::_request_get`](https://github.com/Volcyy/python-twitch-client/blob/api-error-handling/twitch/api/base.py#L46) checks if it got a status code above 500, and if so, passes parameters to the original request to the [`_backoff` function](https://github.com/Volcyy/python-twitch-client/blob/api-error-handling/twitch/api/base.py#L9), which retries the request up to three times with a backoff starting from 0.5 seconds, doubling on every failure.

This has an issue, however: it slows down the tests, specifically [`test_request_get_raises_exception_if_not_200_response`](https://github.com/tsifrer/python-twitch-client/blob/master/tests/api/test_base.py#L76), by around 3.5 seconds due to the default settings. 
Is there a way to pass different keyword arguments through pytest, or should I adjust the parameters? I sadly don't have a lot of experience with test frameworks apart from basic configuration.

**Comment by tsifrer** [comment]
The solution looks quite good. I'd like to keep the backoff functionality in `_request_get` method rather than having a separate function. It should be quite simple to merge the two.

Regarding the `initial_backoff` and `max_retries` I think that should be a global configuration with default values as they are now. We could add a new `General` section to the `~/.twitch.cfg` file (more about the file here http://python-twitch-client.readthedocs.io/en/latest/#authentication).
Then we could have the `_request_get` or a helper function to try and get the `initial_backoff` and `max_retries` from the `~/.twitch.cfg` file and if they don't exist there, then we use the defaults. This could also be used for tests as we could easily mock the function that gets the initial_backoff and max_retries. For example you could look at the code that get's credentials which is a similar case as the backoff https://github.com/tsifrer/python-twitch-client/blob/master/twitch/client.py#L33

**Comment by Volcyy** [comment]
Thanks for the feedback.
I moved the backoff functionality into the `_request_get` function, and moved the backoff modifiers to instance attributes like in [client.py](https://github.com/tsifrer/python-twitch-client/blob/master/twitch/client.py#L14-L18). 

I have a question though: Considering that the `CONFIG_FILE_PATH` is already defined in `client.py`, should I re-use it, move the variable to [`constants.py`](https://github.com/tsifrer/python-twitch-client/blob/master/twitch/constants.py), or should I simply add the same constant to `base.py`? I feel like the latter is not a good idea, since one might forget to modify the variable there when modifying it in another place.

**Comment by Volcyy** [comment]
I opened a pull request, I feel like that's the better place to discuss this anyways. 😄
